//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatilleraApi
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Ahorro
    {
        public int IDAhorro { get; set; }
        public string IDCliente { get; set; }
        public System.DateTime FechaAhorro { get; set; }
        public double ValorAhorrado { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Cliente Cliente { get; set; }
    }
}
