//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatilleraApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int IDPrestamo { get; set; }
        public string IDCliente { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public double ValorPrestado { get; set; }
        public int InteresID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Interes Interes { get; set; }
    }
}
