//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatilleraApi
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Prestamo
    {
        public int IDPrestamo { get; set; }
        public string IDCliente { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public double ValorPrestado { get; set; }
        public double InteresPor { get; set; }
        public double ValorTotalPrestamo { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
          public virtual Cliente Cliente { get; set; }
    }
}
